name: 'setup-docker-scan'
description: 'Setup docker scan'
author: 'Conventional Actions'
inputs:
  scan-version:
    required: false
    description: 'version of docker scan to use'
    default: latest
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: zoom-in
  color: purple
