name: 'setup-docker-scan'
description: 'Setup docker scan'
author: 'Conventional Actions'
inputs:
  scan-version:
    required: false
    description: 'version of docker scan to use'
    default: latest
  token:
    required: false
    description: 'use the authentication token to log into the third-party scanning provider'
runs:
  using: 'node16'
  post: 'dist/setup/index.js'
  main: 'dist/main/index.js'
branding:
  icon: zoom-in
  color: purple
